-- Team 4 - Gym Database SQL file
-- File: drop.sql  
SPOOL project.txt

/* Drop Tables if already there */
DROP TABLE Employee CASCADE CONSTRAINTS;
DROP TABLE Location CASCADE CONSTRAINTS;
DROP TABLE LocationAmenities CASCADE CONSTRAINTS;
DROP TABLE Class CASCADE CONSTRAINTS;
DROP TABLE Member CASCADE CONSTRAINTS;
DROP TABLE ClassEnrolled CASCADE CONSTRAINTS;
DROP TABLE Membership CASCADE CONSTRAINTS;
DROP TABLE Commission CASCADE CONSTRAINTS;

COMMIT;
--
SPOOL OFF


